TOP=../..

include $(TOP)/configure/CONFIG

INC += caConstants.h
INC += version.h

LIBSRCS += version.cpp

LIBRARY = pvAccess

#pvMisc_LIBS += Com

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

