# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/pipelineService

INC += pv/pipelineService.h
INC += pv/pipelineServer.h

pvAccess_SRCS += pipelineService.cpp
pvAccess_SRCS += pipelineServer.cpp
