# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/pipelineService

INC += pv/pipelineService.h
INC += pv/pipelineServer.h

LIBSRCS += pipelineService.cpp
LIBSRCS += pipelineServer.cpp
