# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/pipelineService

INC += pipelineService.h
INC += pipelineServer.h

LIBSRCS += pipelineService.cpp
LIBSRCS += pipelineServer.cpp
