# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/server

INC += pv/serverContext.h
INC += pv/beaconServerStatusProvider.h
INC += pva/server.h

pvAccess_SRCS += responseHandlers.cpp
pvAccess_SRCS += serverContext.cpp
pvAccess_SRCS += serverChannelImpl.cpp
pvAccess_SRCS += baseChannelRequester.cpp
pvAccess_SRCS += beaconEmitter.cpp
pvAccess_SRCS += beaconServerStatusProvider.cpp
pvAccess_SRCS += server.cpp
