# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/ioc

INC += pv/syncChannelFind.h

DBD += PVAServerRegister.dbd
DBD += PVAClientRegister.dbd

LIBSRCS += PVAServerRegister.cpp
LIBSRCS += PVAClientRegister.cpp
