# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/pva

INC += pvaConstants.h
INC += pvaVersion.h
INC += clientFactory.h

LIBSRCS += pvaVersion.cpp
LIBSRCS += clientFactory.cpp
