# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/pva

INC += pv/pvaConstants.h
INC += pv/pvaVersion.h
INC += pv/pvaVersionNum.h
INC += pv/clientFactory.h

LIBSRCS += pvaVersion.cpp
LIBSRCS += clientFactory.cpp
