TOP=../..

include $(TOP)/configure/CONFIG

INC += hexDump.h
INC += wildcharMatcher.h
INC += arrayFIFO.h
INC += growingCircularBuffer.h

LIBSRCS += hexDump.cpp
LIBSRCS += wildcharMatcher.cpp

LIBRARY = pvAccUtils

#pvAccUtils_LIBS += Com

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

