# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/testing

INC += pv/pvaTestClient.h

LIBSRCS += pvaTestClient.cpp
LIBSRCS += pvaTestClientGet.cpp
LIBSRCS += pvaTestClientRPC.cpp
LIBSRCS += pvaTestClientMonitor.cpp
