# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_TEST)/ca

TESTPROD_HOST += testCaProvider
testCaProvider += testCaProvider.cpp
testHarness_SRCS += testCaProvider.cpp
TESTS += testCaProvider
