TOP=..

include $(TOP)/configure/CONFIG

PROD_LIBS += pvAccessCA pvAccess pvData ca Com

TESTPROD_HOST += getme
TESTPROD_HOST += putme
TESTPROD_HOST += monitorme
TESTPROD_HOST += spamme

TESTPROD_HOST += miniget

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

