TOP=..

include $(TOP)/configure/CONFIG

PROD_LIBS += pvAccess pvData ca Com

TESTPROD_HOST += getme

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

