TOP = ..
include $(TOP)/configure/CONFIG
DIRS += client testClient #server
#DIRS += localImpl remoteClientImpl remoteServerImpl
#DIRS += localImplTest remoteImplTest
include $(TOP)/configure/RULES_DIRS

