# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/utils

INC += pv/hexDump.h
INC += pv/logger.h
INC += pv/introspectionRegistry.h
INC += pv/namedLockPattern.h
INC += pv/referenceCountingLock.h
INC += pv/configuration.h
INC += pv/likely.h
INC += pv/wildcard.h
INC += pv/fairQueue.h
INC += pv/requester.h
INC += pv/destroyable.h

pvAccess_SRCS += getgroups.cpp
pvAccess_SRCS += hexDump.cpp
pvAccess_SRCS += inetAddressUtil.cpp
pvAccess_SRCS += logger.cpp
pvAccess_SRCS += introspectionRegistry.cpp
pvAccess_SRCS += configuration.cpp
pvAccess_SRCS += referenceCountingLock.cpp
pvAccess_SRCS += requester.cpp
pvAccess_SRCS += wildcard.cpp
