# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/utils

INC += hexDump.h
INC += inetAddressUtil.h
INC += logger.h
INC += introspectionRegistry.h
INC += namedLockPattern.h
INC += referenceCountingLock.h
INC += configuration.h
INC += likely.h
INC += wildcard.h

LIBSRCS += hexDump.cpp
LIBSRCS += inetAddressUtil.cpp
LIBSRCS += logger.cpp
LIBSRCS += introspectionRegistry.cpp
LIBSRCS += configuration.cpp
LIBSRCS += referenceCountingLock.cpp
LIBSRCS += wildcard.cpp
