# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/utils

INC += pv/hexDump.h
INC += pv/inetAddressUtil.h
INC += pv/logger.h
INC += pv/introspectionRegistry.h
INC += pv/namedLockPattern.h
INC += pv/referenceCountingLock.h
INC += pv/configuration.h
INC += pv/likely.h
INC += pv/wildcard.h
INC += pv/fairQueue.h

LIBSRCS += hexDump.cpp
LIBSRCS += inetAddressUtil.cpp
LIBSRCS += logger.cpp
LIBSRCS += introspectionRegistry.cpp
LIBSRCS += configuration.cpp
LIBSRCS += referenceCountingLock.cpp
LIBSRCS += wildcard.cpp
