TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE


PROD_HOST += examplePvaProcess
examplePvaProcess_SRCS += examplePvaProcess.cpp
examplePvaProcess_LIBS += pva
examplePvaProcess_LIBS += pvAccess
examplePvaProcess_LIBS += pvData
examplePvaProcess_LIBS += Com

PROD_HOST += examplePvaGet
examplePvaGet_SRCS += examplePvaGet.cpp
examplePvaGet_LIBS += pva
examplePvaGet_LIBS += pvAccess
examplePvaGet_LIBS += pvData
examplePvaGet_LIBS += Com

PROD_HOST += examplePvaPut
examplePvaPut_SRCS += examplePvaPut.cpp
examplePvaPut_LIBS += pva
examplePvaPut_LIBS += pvAccess
examplePvaPut_LIBS += pvData
examplePvaPut_LIBS += Com

PROD_HOST += examplePvaMonitor
examplePvaMonitor_SRCS += examplePvaMonitor.cpp
examplePvaMonitor_LIBS += pva
examplePvaMonitor_LIBS += pvAccess
examplePvaMonitor_LIBS += pvData
examplePvaMonitor_LIBS += Com

PROD_HOST += examplePvaMultiDouble
examplePvaMultiDouble_SRCS += examplePvaMultiDouble.cpp
examplePvaMultiDouble_LIBS += pva
examplePvaMultiDouble_LIBS += pvAccess
examplePvaMultiDouble_LIBS += pvData
examplePvaMultiDouble_LIBS += Com

PROD_HOST += examplePvaNTMultiChannel
examplePvaNTMultiChannel_SRCS += examplePvaNTMultiChannel.cpp
examplePvaNTMultiChannel_LIBS += pva
examplePvaNTMultiChannel_LIBS += pvAccess
examplePvaNTMultiChannel_LIBS += nt
examplePvaNTMultiChannel_LIBS += pvData
examplePvaNTMultiChannel_LIBS += Com

PROD_HOST += helloWorldRPC
helloWorldRPC_SRCS += helloWorldRPC.cpp
helloWorldRPC_LIBS += pva
helloWorldRPC_LIBS += pvAccess
helloWorldRPC_LIBS += nt
helloWorldRPC_LIBS += pvData
helloWorldRPC_LIBS += Com

PROD_HOST += helloWorldPutGet
helloWorldPutGet_SRCS += helloWorldPutGet.cpp
helloWorldPutGet_LIBS += pva
helloWorldPutGet_LIBS += pvAccess
helloWorldPutGet_LIBS += nt
helloWorldPutGet_LIBS += pvData
helloWorldPutGet_LIBS += Com

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

