# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESSAPP)/v3ioc

INC += syncChannelFind.h

DBD += PVAServerRegister.dbd
DBD += PVAClientRegister.dbd

LIBSRCS += PVAServerRegister.cpp
LIBSRCS += PVAClientRegister.cpp
