# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/client

INC += pv/monitor.h
INC += pv/pvAccess.h
INC += pva/client.h

LIBSRCS += pvAccess.cpp
LIBSRCS += client.cpp
LIBSRCS += clientSync.cpp
LIBSRCS += clientGet.cpp
LIBSRCS += clientRPC.cpp
LIBSRCS += clientMonitor.cpp
