# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/client

INC += pv/monitor.h
INC += pv/pvAccess.h
INC += pva/client.h

pvAccess_SRCS += pvAccess.cpp
pvAccess_SRCS += monitor.cpp
pvAccess_SRCS += client.cpp
pvAccess_SRCS += clientSync.cpp
pvAccess_SRCS += clientGet.cpp
pvAccess_SRCS += clientPut.cpp
pvAccess_SRCS += clientRPC.cpp
pvAccess_SRCS += clientMonitor.cpp
pvAccess_SRCS += clientInfo.cpp
