# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/remote

INC += pv/remote.h
INC += pv/security.h
INC += pv/blockingUDP.h
INC += pv/beaconHandler.h
INC += pv/blockingTCP.h
INC += pv/channelSearchManager.h
INC += pv/simpleChannelSearchManagerImpl.h
INC += pv/transportRegistry.h
INC += pv/serializationHelper.h
INC += pv/codec.h

LIBSRCS += blockingUDPTransport.cpp
LIBSRCS += blockingUDPConnector.cpp
LIBSRCS += beaconHandler.cpp
LIBSRCS += blockingTCPConnector.cpp
LIBSRCS += simpleChannelSearchManagerImpl.cpp
LIBSRCS += abstractResponseHandler.cpp
LIBSRCS += blockingTCPAcceptor.cpp
LIBSRCS += transportRegistry.cpp
LIBSRCS += serializationHelper.cpp
LIBSRCS += codec.cpp
LIBSRCS += security.cpp
