# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/ca

INC += caProvider.h
INC += caChannel.h
INC += caStatus.h

LIBSRCS += caProvider.cpp
LIBSRCS += caChannel.cpp
LIBSRCS += caStatus.cpp
