# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVACCESS_SRC)/ca

LIBRARY += pvAccessCA
pvAccessCA_LIBS += ca pvAccess pvData Com

INC += pv/caProvider.h
INC += pv/caChannel.h
INC += pv/caStatus.h

pvAccessCA_SRCS += caProvider.cpp
pvAccessCA_SRCS += caChannel.cpp
pvAccessCA_SRCS += caStatus.cpp
